#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr -s 1024x576  		# Set DPI. User may want to use a larger number for larger screens.
#xbacklight -set 1.0 &
light -S 1.0 &
/usr/bin/lxpolkit &
#cbatticon -u 60 -i symbolic -c "poweroff" -l 20 -r 5 &
setbg &			# set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
pgrep redshift &> /dev/null ||redshift &> /dev/null &
autostart="mpd xcompmgr dunst unclutter "

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
